export type Platform = 'wordpress' | 'shopify' | 'html'

export interface Product {
  id: string
  title: string
  description: string
  category: string
  type: 'theme' | 'plugin' | 'starter'
  platform: Platform
  price: number
  compareAtPrice?: number
  author: string
  image: string
  tags: string[]
  reviews: number
  rating: number
  featured: boolean
  badge?: string
  inStock: boolean
  sales?: number
}

export interface Collection {
  id: string
  name: string
  description: string
  count: number
}

export interface PlatformInfo {
  id: Platform
  name: string
  description: string
  icon: string
}

export const platforms: PlatformInfo[] = [
  { id: 'wordpress', name: 'WordPress', description: 'Themes for WordPress CMS', icon: 'wordpress' },
  { id: 'shopify', name: 'Shopify', description: 'Themes for Shopify stores', icon: 'shopify' },
  { id: 'html', name: 'HTML', description: 'Static HTML templates', icon: 'html' },
]

export const collections: Collection[] = [
  { id: 'all', name: 'All Themes', description: 'Browse all themes and templates', count: 18 },
  { id: 'business', name: 'Business', description: 'Corporate and business themes', count: 5 },
  { id: 'ecommerce', name: 'eCommerce', description: 'Online store themes', count: 5 },
  { id: 'blog', name: 'Blog & Magazine', description: 'Content focused themes', count: 3 },
  { id: 'portfolio', name: 'Portfolio', description: 'Showcase your work', count: 4 },
  { id: 'starter', name: 'Starter Kits', description: 'Quick start templates', icon: 'starter', count: 3 },
]

export const products: Product[] = [
  // WordPress Themes
  {
    id: '1',
    title: 'Flavor Business Theme',
    description: 'Multi-purpose WordPress theme with 50+ demos, Elementor builder, and WooCommerce integration.',
    category: 'business',
    type: 'theme',
    platform: 'wordpress',
    price: 59,
    author: 'ThemeForest Elite',
    image: '/templates/flavor-business.jpg',
    tags: ['Elementor', 'WooCommerce', 'Responsive'],
    reviews: 2847,
    rating: 4.9,
    featured: true,
    badge: 'Bestseller',
    inStock: true,
    sales: 45200,
  },
  {
    id: '2',
    title: 'ShopMax WooCommerce',
    description: 'Premium eCommerce theme built for WooCommerce with advanced product filtering and Ajax cart.',
    category: 'ecommerce',
    type: 'theme',
    platform: 'wordpress',
    price: 69,
    compareAtPrice: 89,
    author: 'PixelPro Studio',
    image: '/templates/shopmax-woo.jpg',
    tags: ['WooCommerce', 'Shop', 'Ajax'],
    reviews: 1523,
    rating: 4.8,
    featured: true,
    badge: 'Sale',
    inStock: true,
    sales: 28400,
  },
  {
    id: '3',
    title: 'Developer Portfolio Pro',
    description: 'Clean minimal portfolio theme for developers and designers with dark mode and project showcase.',
    category: 'portfolio',
    type: 'theme',
    platform: 'wordpress',
    price: 0,
    author: 'DevThemes',
    image: '/templates/developer-portfolio.jpg',
    tags: ['Portfolio', 'Minimal', 'Developer'],
    reviews: 892,
    rating: 4.7,
    featured: true,
    badge: 'Free',
    inStock: true,
    sales: 67800,
  },
  {
    id: '4',
    title: 'NewsPress Magazine',
    description: 'Fast and SEO-optimized magazine theme with multiple layouts, ad management, and AMP support.',
    category: 'blog',
    type: 'theme',
    platform: 'wordpress',
    price: 49,
    author: 'MagPro Themes',
    image: '/templates/newspress-mag.jpg',
    tags: ['Magazine', 'News', 'SEO'],
    reviews: 1876,
    rating: 4.8,
    featured: true,
    inStock: true,
    sales: 31500,
  },
  {
    id: '5',
    title: 'Corporate Elite',
    description: 'Professional business theme with booking system, team management, and service showcases.',
    category: 'business',
    type: 'theme',
    platform: 'wordpress',
    price: 79,
    compareAtPrice: 99,
    author: 'ThemeForest Elite',
    image: '/templates/corporate-elite.jpg',
    tags: ['Corporate', 'Business', 'Booking'],
    reviews: 723,
    rating: 4.6,
    featured: false,
    badge: 'Popular',
    inStock: true,
    sales: 18900,
  },
  {
    id: '6',
    title: 'Blog Starter Kit',
    description: 'Starter theme with modular design, custom widgets, and lifetime updates.',
    category: 'blog',
    type: 'starter',
    platform: 'wordpress',
    price: 39,
    author: 'Starter Labs',
    image: '/templates/developer-starter.jpg',
    tags: ['Starter', 'Blog', 'Modular'],
    reviews: 2134,
    rating: 4.9,
    featured: false,
    badge: 'Top Rated',
    inStock: true,
    sales: 52300,
  },
  
  // Shopify Themes
  {
    id: '7',
    title: 'Dawn Pro - Shopify 2.0',
    description: 'Premium Shopify 2.0 theme with sections everywhere, optimized checkout, and mobile-first design.',
    category: 'ecommerce',
    type: 'theme',
    platform: 'shopify',
    price: 89,
    author: 'Shopify Experts',
    image: '/templates/shopify-dawn-pro.jpg',
    tags: ['Shopify 2.0', 'Sections', 'Mobile'],
    reviews: 1234,
    rating: 4.9,
    featured: true,
    badge: 'Bestseller',
    inStock: true,
    sales: 34500,
  },
  {
    id: '8',
    title: 'Luxe Fashion Store',
    description: 'Elegant fashion Shopify theme with lookbook, quick view, advanced filtering, and Instagram shop.',
    category: 'ecommerce',
    type: 'theme',
    platform: 'shopify',
    price: 99,
    compareAtPrice: 149,
    author: 'FashionThemes',
    image: '/templates/shopify-luxe-fashion.jpg',
    tags: ['Fashion', 'Lookbook', 'Instagram'],
    reviews: 876,
    rating: 4.8,
    featured: true,
    badge: 'Sale',
    inStock: true,
    sales: 21300,
  },
  {
    id: '9',
    title: 'Beauty & Cosmetics',
    description: 'Stunning Shopify theme for beauty brands with product bundles, subscriptions, and reward points.',
    category: 'ecommerce',
    type: 'theme',
    platform: 'shopify',
    price: 79,
    author: 'BeautyThemes',
    image: '/templates/shopify-beauty-store.jpg',
    tags: ['Beauty', 'Cosmetics', 'Subscriptions'],
    reviews: 654,
    rating: 4.7,
    featured: false,
    badge: 'New',
    inStock: true,
    sales: 12800,
  },
  {
    id: '10',
    title: 'Minimal Shopify Starter',
    description: 'Clean minimal Shopify starter theme, perfect for small stores and dropshipping businesses.',
    category: 'starter',
    type: 'starter',
    platform: 'shopify',
    price: 0,
    author: 'StartupThemes',
    image: '/templates/shopify-minimal-starter.jpg',
    tags: ['Minimal', 'Starter', 'Dropship'],
    reviews: 2341,
    rating: 4.6,
    featured: false,
    badge: 'Free',
    inStock: true,
    sales: 89200,
  },
  {
    id: '11',
    title: 'Electronics Mega Store',
    description: 'Feature-rich Shopify theme for electronics with mega menu, comparison, and spec tables.',
    category: 'ecommerce',
    type: 'theme',
    platform: 'shopify',
    price: 109,
    author: 'TechThemes',
    image: '/templates/shopify-electronics.jpg',
    tags: ['Electronics', 'Mega Menu', 'Compare'],
    reviews: 543,
    rating: 4.8,
    featured: false,
    badge: 'Popular',
    inStock: true,
    sales: 15600,
  },

  // HTML Templates
  {
    id: '12',
    title: 'Startup Landing Page',
    description: 'Modern HTML5 landing page template with animations, pricing tables, and contact forms.',
    category: 'business',
    type: 'theme',
    platform: 'html',
    price: 29,
    author: 'LaunchThemes',
    image: '/templates/html-startup-landing.jpg',
    tags: ['Landing', 'Startup', 'Animations'],
    reviews: 1567,
    rating: 4.8,
    featured: true,
    badge: 'Bestseller',
    inStock: true,
    sales: 42100,
  },
  {
    id: '13',
    title: 'Developer Portfolio HTML',
    description: 'Creative HTML portfolio template for developers with project showcase, skills, and blog.',
    category: 'portfolio',
    type: 'theme',
    platform: 'html',
    price: 19,
    author: 'DevTemplates',
    image: '/templates/html-developer-portfolio.jpg',
    tags: ['Portfolio', 'Developer', 'Creative'],
    reviews: 987,
    rating: 4.7,
    featured: true,
    badge: 'Popular',
    inStock: true,
    sales: 28900,
  },
  {
    id: '14',
    title: 'Agency Starter Kit',
    description: 'Complete HTML agency template with services, team, case studies, and contact sections.',
    category: 'business',
    type: 'starter',
    platform: 'html',
    price: 0,
    author: 'AgencyPro',
    image: '/templates/html-agency-starter.jpg',
    tags: ['Agency', 'Starter', 'Services'],
    reviews: 1876,
    rating: 4.9,
    featured: true,
    badge: 'Free',
    inStock: true,
    sales: 67400,
  },
  {
    id: '15',
    title: 'Restaurant HTML Template',
    description: 'Beautiful restaurant HTML template with menu builder, reservation form, and gallery.',
    category: 'business',
    type: 'theme',
    platform: 'html',
    price: 35,
    author: 'FoodThemes',
    image: '/templates/html-restaurant.jpg',
    tags: ['Restaurant', 'Food', 'Menu'],
    reviews: 654,
    rating: 4.6,
    featured: false,
    inStock: true,
    sales: 13200,
  },
  {
    id: '16',
    title: 'Photography Portfolio',
    description: 'Stunning HTML photography portfolio with fullscreen galleries, lightbox, and lazy loading.',
    category: 'portfolio',
    type: 'theme',
    platform: 'html',
    price: 25,
    author: 'PhotoThemes',
    image: '/templates/html-photography.jpg',
    tags: ['Photography', 'Gallery', 'Lightbox'],
    reviews: 543,
    rating: 4.8,
    featured: false,
    badge: 'New',
    inStock: true,
    sales: 9800,
  },
  {
    id: '17',
    title: 'SaaS Dashboard UI',
    description: 'Complete HTML/CSS dashboard template with charts, tables, forms, and dark mode.',
    category: 'business',
    type: 'theme',
    platform: 'html',
    price: 49,
    compareAtPrice: 79,
    author: 'DashboardPro',
    image: '/templates/html-dashboard.jpg',
    tags: ['Dashboard', 'Admin', 'Charts'],
    reviews: 1234,
    rating: 4.9,
    featured: false,
    badge: 'Sale',
    inStock: true,
    sales: 23400,
  },
  {
    id: '18',
    title: 'Creative Agency HTML',
    description: 'Bold creative agency template with parallax effects, portfolio slider, and animations.',
    category: 'portfolio',
    type: 'theme',
    platform: 'html',
    price: 39,
    author: 'CreativeStack',
    image: '/templates/html-creative-agency.jpg',
    tags: ['Agency', 'Creative', 'Parallax'],
    reviews: 765,
    rating: 4.7,
    featured: false,
    inStock: true,
    sales: 16700,
  },
]
