export interface Product {
  id: string
  title: string
  description: string
  category: string
  type: 'theme' | 'plugin' | 'starter'
  price: number
  compareAtPrice?: number
  author: string
  image: string
  tags: string[]
  reviews: number
  rating: number
  featured: boolean
  badge?: string
  inStock: boolean
  sales?: number
}

export interface Collection {
  id: string
  name: string
  description: string
  count: number
}

export const collections: Collection[] = [
  { id: 'all', name: 'All Themes', description: 'Browse all WordPress themes', count: 12 },
  { id: 'business', name: 'Business', description: 'Corporate and business themes', count: 4 },
  { id: 'ecommerce', name: 'eCommerce', description: 'WooCommerce ready themes', count: 3 },
  { id: 'blog', name: 'Blog & Magazine', description: 'Content focused themes', count: 3 },
  { id: 'portfolio', name: 'Portfolio', description: 'Showcase your work', count: 2 },
]

export const products: Product[] = [
  {
    id: '1',
    title: 'Flavor Business Theme',
    description: 'Multi-purpose WordPress theme with 50+ demos, Elementor builder, and WooCommerce integration.',
    category: 'business',
    type: 'theme',
    price: 59,
    author: 'ThemeForest Elite',
    image: '/templates/flavor-business.jpg',
    tags: ['Elementor', 'WooCommerce', 'Responsive'],
    reviews: 2847,
    rating: 4.9,
    featured: true,
    badge: 'Bestseller',
    inStock: true,
    sales: 45200,
  },
  {
    id: '2',
    title: 'ShopMax WooCommerce',
    description: 'Premium eCommerce theme built for WooCommerce with advanced product filtering and Ajax cart.',
    category: 'ecommerce',
    type: 'theme',
    price: 69,
    compareAtPrice: 89,
    author: 'PixelPro Studio',
    image: '/templates/shopmax-woo.jpg',
    tags: ['WooCommerce', 'Shop', 'Ajax'],
    reviews: 1523,
    rating: 4.8,
    featured: true,
    badge: 'Sale',
    inStock: true,
    sales: 28400,
  },
  {
    id: '3',
    title: 'Developer Portfolio Pro',
    description: 'Clean minimal portfolio theme for developers and designers with dark mode and project showcase.',
    category: 'portfolio',
    type: 'theme',
    price: 0,
    author: 'DevThemes',
    image: '/templates/developer-portfolio.jpg',
    tags: ['Portfolio', 'Minimal', 'Developer'],
    reviews: 892,
    rating: 4.7,
    featured: true,
    badge: 'Free',
    inStock: true,
    sales: 67800,
  },
  {
    id: '4',
    title: 'NewsPress Magazine',
    description: 'Fast and SEO-optimized magazine theme with multiple layouts, ad management, and AMP support.',
    category: 'blog',
    type: 'theme',
    price: 49,
    author: 'MagPro Themes',
    image: '/templates/newspress-mag.jpg',
    tags: ['Magazine', 'News', 'SEO'],
    reviews: 1876,
    rating: 4.8,
    featured: true,
    inStock: true,
    sales: 31500,
  },
  {
    id: '5',
    title: 'Corporate Elite',
    description: 'Professional business theme with booking system, team management, and service showcases.',
    category: 'business',
    type: 'theme',
    price: 79,
    compareAtPrice: 99,
    author: 'ThemeForest Elite',
    image: '/templates/corporate-elite.jpg',
    tags: ['Corporate', 'Business', 'Booking'],
    reviews: 723,
    rating: 4.6,
    featured: false,
    badge: 'Popular',
    inStock: true,
    sales: 18900,
  },
  {
    id: '6',
    title: 'Blog starter starter kit',
    description: 'Starter theme with modular design, custom widgets, and lifetime updates.',
    category: 'blog',
    type: 'starter',
    price: 39,
    author: 'starter Labs',
    image: '/templates/developer-starter.jpg',
    tags: ['starter', 'Starter', 'Modular'],
    reviews: 2134,
    rating: 4.9,
    featured: false,
    badge: 'Top Rated',
    inStock: true,
    sales: 52300,
  },
  {
    id: '7',
    title: 'Flavor Store Theme',
    description: 'Flavor variant optimized for large product catalogs with mega menu and quick view.',
    category: 'ecommerce',
    type: 'theme',
    price: 69,
    author: 'ThemeForest Elite',
    image: '/templates/flavor-store.jpg',
    tags: ['WooCommerce', 'Flavor', 'Mega Menu'],
    reviews: 956,
    rating: 4.7,
    featured: false,
    inStock: true,
    sales: 23100,
  },
  {
    id: '8',
    title: 'Creative Agency Theme',
    description: 'Bold and creative theme for agencies with portfolio, case studies, and testimonial sections.',
    category: 'portfolio',
    type: 'theme',
    price: 55,
    author: 'CreativeStack',
    image: '/templates/creative-agency.jpg',
    tags: ['Agency', 'Creative', 'Portfolio'],
    reviews: 612,
    rating: 4.8,
    featured: false,
    badge: 'New',
    inStock: true,
    sales: 12400,
  },
  {
    id: '9',
    title: 'SaaS Landing Theme',
    description: 'Modern SaaS landing page theme with pricing tables, feature sections, and integration showcases.',
    category: 'business',
    type: 'theme',
    price: 45,
    author: 'LaunchThemes',
    image: '/templates/saas-landing.jpg',
    tags: ['SaaS', 'Landing', 'Startup'],
    reviews: 487,
    rating: 4.6,
    featured: false,
    inStock: true,
    sales: 9800,
  },
  {
    id: '10',
    title: 'Travel Blog Theme',
    description: 'Beautiful travel blog theme with maps integration, trip galleries, and destination guides.',
    category: 'blog',
    type: 'theme',
    price: 49,
    compareAtPrice: 69,
    author: 'WanderThemes',
    image: '/templates/travel-blog.jpg',
    tags: ['Travel', 'Blog', 'Maps'],
    reviews: 1245,
    rating: 4.7,
    featured: false,
    badge: 'Sale',
    inStock: true,
    sales: 26700,
  },
  {
    id: '11',
    title: 'Restaurant Theme',
    description: 'Complete restaurant theme with menu builder, reservation system, and delivery integration.',
    category: 'business',
    type: 'theme',
    price: 59,
    author: 'FoodThemes',
    image: '/templates/restaurant-theme.jpg',
    tags: ['Restaurant', 'Food', 'Booking'],
    reviews: 834,
    rating: 4.8,
    featured: false,
    inStock: true,
    sales: 19200,
  },
  {
    id: '12',
    title: 'Fashion Store Theme',
    description: 'Elegant fashion eCommerce theme with lookbook, size guide, and Instagram integration.',
    category: 'ecommerce',
    type: 'theme',
    price: 75,
    author: 'StyleThemes',
    image: '/templates/fashion-store.jpg',
    tags: ['Fashion', 'WooCommerce', 'Lookbook'],
    reviews: 1087,
    rating: 4.9,
    featured: false,
    badge: 'Trending',
    inStock: true,
    sales: 21600,
  },
]
